Feature: first design console
project-march/monitor pull request #1
Opened 2019-11-05 10:01 UTC by Olavhaasie

Closes PM-29

## Description
This PR adds a design for the minute taking Qt plugin. It provides a UI that can be used to enter messages. The only functionality that has been implemented is entering messages, it currently does not listen to any topics.

![image](https://user-images.githubusercontent.com/23523462/68197691-f0c5b700-ffba-11e9-8e34-2db6b7623020.png)

This can replace the `march_rqt_training_log` functionality. This plugin should filter messages and topics and publish messages relevant to the training process. See PM-15 for more information.

## Changes
* Added `march_rqt_console` package
* Added basic `console.ui`

2019-11-05 11:07 UTC, RutgerVanBeek reviewed
How would you add your message to the console? Shouldn't there be a button for this. 
What would you load and save with the buttons ?
How would you delete a message you added?

2019-11-05 11:13 UTC, Olavhaasie commented
> How would you add your message to the console? Shouldn't there be a button for this.

In the input field at the bottom you can type your minutes and press enter to submit them. I wanted to keep the GUI clean, so I left out a button.

> What would you load and save with the buttons ?

You could save all the current messages to a file in a nice format or in csv.

> How would you delete a message you added?

This does not work yet, but you can select the messages from the table and delete them with your delete key or we could implement a right click menu with more options.

2019-11-05 11:20 UTC, RutgerVanBeek submitted a review, later dismissed

2019-11-05 16:46 UTC, Roelemans reviewed
Why is this called console? I would interpret that as a menu from which you could launch other rqt plugins and the like. Maybe call it note_taker/notes/minutes/minute_taker? Why do you add a "level" column? I think only "error/fatal" would be a relevant level, but you might as well just include that in the message (which you probably will anyway). Perhaps you could use the column to add labels like "error/fatal" and (emergency button) "pressed", "todo" etc. 

How exactly would the camera take work? Does it send a message when you change the take?

2019-11-05 16:46 UTC, Roelemans commented on march_rqt_console/src/march_rqt_console/message.py
> +class Message(QObject):
Shouldn't you better call this LogEntry or something to avoid confusion with ros messages?

2019-11-05 17:22 UTC, Olavhaasie commented
> Why is this called console? I would interpret that as a menu from which you could launch other rqt plugins and the like. Maybe call it note_taker/notes/minutes/minute_taker?

I copied the name from `rqt_console` and forgot to give it a descriptive name, so good point, I will call it... `march_note_taker` :confetti_ball: 

> Why do you add a "level" column? I think only "error/fatal" would be a relevant level, but you might  as well just include that in the message (which you probably will anyway). Perhaps you could use the column to add labels like "error/fatal" and (emergency button) "pressed", "todo" etc.

I agree, we can give the logs a color like red for error/fatal and just gray for info. And use the column for tags.

> How exactly would the camera take work? Does it send a message when you change the take?

Precisely my idea :innocent: Do you have any other ideas?

2019-11-05 19:19 UTC, Roelemans commented
> Precisely my idea :innocent: Do you have any other ideas?

I think it is a bit strange to have a take "scroller" like you have here (if you scroll it would send multiple messages). Also, sometimes you jump from take 3 to take 7 due to failed takes. Maybe either
1) add an "add camera take" button (or shortcut)? 
2) when you change the camera take, it adds a message to the text bar for logging; which is replaced when you change it again (so you would still have to press enter to send the message). Would have to think about what to do when there is already an unfinished message present in the text bar
3) Add a message to the log which is replaced when the take is changed again within a certain time slot/or so long as no custom message is send

2019-11-05 19:47 UTC, Olavhaasie commented
> add an "add camera take" button (or shortcut)?

Then I would go with your first idea with button as well as shortcut. Since that is easy to implement and use.

2019-11-06 13:09 UTC, Roelemans requested changes

2019-11-06 13:09 UTC, Roelemans commented on march_rqt_note_taker/src/march_rqt_note_taker/notes_plugin.py
> +        ui_file = os.path.join(rospkg.RosPack().get_path('march_rqt_note_taker'), 'resource', 'plugin.ui')
```suggestion
        ui_file = os.path.join(rospkg.RosPack().get_path('march_rqt_note_taker'), 'resource', 'note_taker.ui')
```

2019-11-06 13:09 UTC, Roelemans commented on march_rqt_note_taker/resource/plugin.ui
> +   <string>Console</string>
```suggestion
   <string>Note taker</string>
```

2019-11-06 13:09 UTC, Roelemans commented on march_rqt_note_taker/plugin.xml
> +            <label>March Minutes</label>
```suggestion
            <label>March note taker</label>
```

2019-11-06 13:09 UTC, Roelemans commented on march_rqt_note_taker/plugin.xml
> +            <statustip>March Minutes</statustip>
```suggestion
            <statustip>March note taker</statustip>
```

2019-11-06 13:22 UTC, Roelemans requested changes

2019-11-06 13:22 UTC, Roelemans commented on march_rqt_note_taker/resource/note_taker.ui
> +   <string>Console</string>
```suggestion
   <string>Note taker</string>
```

2019-11-06 16:06 UTC, Roelemans approved these changes
Took you long enough

2019-11-06 16:06 UTC, merged