Add slope down button
project-march/monitor pull request #13
Opened 2019-12-03 12:37 UTC by marnixbrands

## Description
 Add slope down gait buttons to input device

## Changes
 Added two buttons to input device for the slope down gaits

2019-12-03 14:22 UTC, RutgerVanBeek reviewed
Approved when state machine is changed as well.

2019-12-04 15:06 UTC, Olavhaasie requested changes

2019-12-04 15:06 UTC, Olavhaasie commented on march_rqt_input_device/src/march_rqt_input_device/input_device.py
> +                                               text='MV Ramp and Door last step',
You can name them `Slope down` and `Slope last step`, since these are not bound to MV gaits

2019-12-05 09:52 UTC, Olavhaasie approved these changes

2019-12-05 15:12 UTC, RutgerVanBeek approved these changes
Nice, for the future it would be nice to say how this can be tested. Like in which repositories we should pull and which gait file folder we can use.

2019-12-05 15:12 UTC, merged