Feature/pm 335 multiplot configs
project-march/monitor pull request #31
Opened 2020-03-23 15:12 UTC by RutgerVanBeek

Closes PM-335

## Description

This reintroduces the central folder for rqt_multiplot configurations. Making this available for everyone should help in getting the necessary plots fast. 

Some general commetns:
* I have set all the axis labels with units (if applicable), but turned them off, to make the plot bigger. They can easily be shown by opening the plot configuration (you only have to select the checkbox as the name is already correct).
* I have decided to make configuration rather have to little than too many plots as it is easier to remove then to add things. 
* In general I have used the time stamp from the message as the the time, because this is more reliable and in some cases there is no clock running (when playing a bag file). Exception to this is the update of PID parameters as these messages do not contain a header.
*  All time-axis are set to show the last 10 seconds. 
* All y-axis are set to automatic scaling. Exception is the temperature as we don't want temperatures above 100 to fuck up our graph. 

Available plots:
*  **actual_desired:** This plots the actual and desired position for each joint separately. 
* **controller_output:** This plots the controller output for each joint. Next to that it plots the after limit joint command to see the effect of the safety controller. 
* **joint_values:** Plots the actual position, velocity, acceleration and jerk for each joint. 
* **pid_terms**: Plots the amount the P, I and D are contributing to the effort command for each joint. 
* **pid_updates:** Plots the P, I and D values us updated by gain scheduling. This is the only plot that is not a line plot as the frequency of updating can also be of interest. 
* **temperature:** Plots the temperature for each joint. 
* **controller_per_joint folder:** This is a folder with a configuration for each joint. The configuration contains the actual/desired position, the error in position, after limit joint command, actual effort, error dot and actual/desired velocity, but just for one joint. 

## Changes

* Added a folder with a lot of _rqt_multiplot_ configurations.

2020-03-23 16:19 UTC, Olavhaasie submitted a review, later dismissed
Good job, I have tested a few, so let's hope they all work :crossed_fingers:

2020-03-23 16:56 UTC, Roelemans requested changes
Very very nice! Your really put in some effort :O 
A few comments on axis:
For the temprature plot, the axis are automatic instead of relative. Is this on purpose? Maybe nice indeed to see temprature over entire time
PID_update plot has absolute  y-axis. Perhaps relative is better here?
Controller_output plots points instead of lines.

2020-03-24 08:35 UTC, Olavhaasie approved these changes

2020-03-24 08:45 UTC, Roelemans approved these changes

2020-03-24 09:50 UTC, merged