Feature/pm 511 paramatric gaits in rqt
project-march/monitor pull request #63
Opened 2020-07-22 11:36 UTC by RutgerVanBeek

Closes PM-511

## Description

I have made added an extra option to the subgait versiosn to choose from, called "parametric". When choosing this version a pop-up will appear. In this pop-up one can choose a parameter and versions for the parametric gait. This is then stored as a versions string with the following format: '_{parameter}_({base version})_({other version})'. 
## Changes

* Added a pop up menu for creating a parametric gait. 

## Testing
Test this with the corresponding branch in the March repo, otherwise it will not be able to find files with this version.

2020-07-23 14:40 UTC, Olavhaasie requested changes
Looks good! I think in the future, when this could be expanded another way of handling the parameters will be necessary. For example, if you want more parameters the version string would become very long.

Also another small point. Perhaps you could add a small description next to the parameter input field, to describe what it does?

2020-07-23 14:40 UTC, Olavhaasie commented on march_rqt_gait_selection/src/march_rqt_gait_selection/gait_selection_view.py
> +                            subgait_menu.setCurrentIndex(current_version_index - 1)
When the `current_version_index` is 0 you get an out of bounds. You can try by choosing parametric on a subgait with only 1 subgait version and then closing it.

2020-07-23 14:40 UTC, Olavhaasie commented on march_rqt_gait_selection/src/march_rqt_gait_selection/parametric_pop_up.py
> +class ParametricPopUpWindow(QDialog):
You could also create a `.ui` file for this, just like the main widget and load it.

2020-07-24 12:49 UTC, JorisWeeda commented on march_rqt_gait_selection/src/march_rqt_gait_selection/gait_selection_view.py
> +        self._parametric_pop_up.show_pop_up()
should this function not have the `versions` variable populated?

2020-07-24 12:51 UTC, Joris-JW requested changes
since one of the drop-down options triggers a pop up menu maybe it is nice to disable the scrolling through the drop-down with the mouse wheel, just to prevent sudden popups. furthermore, looks good and works nice :fire: 

And what olav said might be nice (about thedescription) and i think the quickest way would be to add a tooltip when dragging the mouse over the parameter label. This is very easy to implement using a `.ui` file

2020-07-29 08:12 UTC, Olavhaasie requested changes
I don't know why but my popup looks like this. It could have something to do with my resolution, but the normal rqt plugin is fine.

![image](https://user-images.githubusercontent.com/23523462/88774105-8e2cd080-d172-11ea-9a76-2ff0382620ac.png)

Also a box and slider would be nice for inputting the parameter. Similar to what we use for the time slider in the gait generation. Also, you wouldn't have to update the label every time.

2020-07-29 08:12 UTC, Olavhaasie commented on march_rqt_gait_selection/resource/parametric_pop_up.ui
> +       <string extracomment="The parametric subgait would result to this version if the parameter is 0%.">The parametric subgait would result to this version if the parameter is 0%.</string>
```suggestion
       <string extracomment="The parametric subgait would result in this version if the parameter is 0%.">The parametric subgait would result in this version if the parameter is 0%.</string>
```

2020-07-29 08:12 UTC, Olavhaasie commented on march_rqt_gait_selection/resource/parametric_pop_up.ui
> +       <string extracomment="The parametric subgait would result to this version if the parameter is 100%.">The parametric subgait would result to this version if the parameter is 100%.</string>
```suggestion
       <string extracomment="The parametric subgait would result in this version if the parameter is 100%.">The parametric subgait would result in this version if the parameter is 100%.</string>
```

2020-07-29 21:33 UTC, Olavhaasie approved these changes
Everything looks good now :+1:

If you want to and if have some time left you could take a look at my other suggestion :innocent: 

> Also a box and slider would be nice for inputting the parameter. Similar to what we use for the time slider in the gait generation. Also, you wouldn't have to update the label every time.

2020-07-30 15:14 UTC, RutgerVanBeek commented
> Also a box and slider would be nice for inputting the parameter. Similar to what we use for the time slider in the gait generation. Also, you wouldn't have to update the label every time.

What is the difference with the current slider. What would you like to see different?
I think updating the label is nice, to see the exact value you chose. (Say you want to do exactly 50%).

2020-07-31 07:51 UTC, Olavhaasie commented
> > Also a box and slider would be nice for inputting the parameter. Similar to what we use for the time slider in the gait generation. Also, you wouldn't have to update the label every time.
> 
> What is the difference with the current slider. What would you like to see different?
> I think updating the label is nice, to see the exact value you chose. (Say you want to do exactly 50%).

I had this idea of using a input box and a slider, so that you could enter 0.5 exactly without having to slide it, or just estimate a value with the slider. But it's not that important, so nevermind unless you want to implement it yourself.

2020-08-03 12:25 UTC, Joris-JW approved these changes
:100:

2020-08-03 12:27 UTC, merged